### PR TITLE
Tasks36-41Done

### LINKED ISSUE #36: Change router paths
### Explanation
Art Marketplace is a portfolio project that uses as a base a real project of one real client, that is the reason why some things remain the same as the other project. As an example of it we have the routes. I have found some routes that refer to products instead of art, for example. I will add a list of routes to change in the checklist, but I would like you to check and let me know if other route looks weird! 

### Screenshots
Say "products" the URL, but this view is not about products else about artworks
imagen

### Checklist
 Describe the key points to complete the task. This points will help in the pull request test.

 This issue can be closed when the following tasks are completed:
 
 - [ ] `/products/` link has been changed. I think it should be some like `/artworks/` or `/all/`, but I accept suggestions.
 - [ ] `/product/{id}` have been changed. I think should be some like `/artwork/{id}` but I´m open minded, and accept suggestions.
 - [ ] Check if another route exists that can be improved.

### LINKED ISSUE #41: Round the login form container borders
### Explanation
The borders on the box of the login are 0px rounded, but at figma design this has `border-radius: 10px;`.

### Screenshots
imagen.

### Checklist
 This issue can be closed when the following tasks are completed:
 
 - [ ] Now the box have border-radius: 10px or looks like the design.
 
### References
 - https://www.figma.com/file/zzEwuPfGTiZh4EA11MyZ5c/Sencico?node-id=0%3A1

### PR DESCRIPTION
**Pull request by ygamboalh**
Task #36
When using tailwind css, the border radius asked to fix the box of the login, cant be set to 10px due to we can only use round-lg, that is the closer we can get. In that case round-lg is a 0.5rem radius which is 8px, the same used for the inputs. 
 Task #41 
The name of the path /products was changed into /artworks and /product/{id} into /artwork/{id}. 
In order to make it work I had to chance a few files: Home.js, ObjectList, Filters.jsx,ProductItem.jsx, ProductsActions.

### CODE REVIEW

**Review by heliomar-pena — APPROVED** [review]
I see it good, good work

**Comment by angelik0828** [comment]
Checking task 36 of the links I can see that it changed when entering the main page, but when entering the category slider the product link is still there, and it does not load, attached image of the link to the page. @Rapsodian 

task 41 change is ok

image

image

**Comment by heliomar-pena** [comment]
> Checking task 36 of the links I can see that it changed when entering the main page, but when entering the category slider the product link is still there, and it does not load, attached image of the link to the page. @Rapsodian

I confirm, when you select a category, they redirect you to "/products?category" and how "/products" doesn't exist, I only see a blank page

**Comment by ygamboalh** [comment]
> Checking task 36 of the links I can see that it changed when entering the main page, but when entering the category slider the product link is still there, and it does not load, attached image of the link to the page. @Rapsodian
> 
> task 41 change is ok
> 
> image
> 
> image

Ok, I can see it now. I will solve the problem.

**Comment by ygamboalh** [comment]
Task #36 is ready for review now.

**Review by heliomar-pena — APPROVED** [review]
I check and is working well! Very thanks for check and solve our comments

**Comment by heliomar-pena** [comment]
Doing click in some category:
imagen

Doing click in some subcategory:
imagen

Doing click in some product:
imagen

Doing a search:
imagen

As you see it's working well in most cases, but still is missing the "search". I wrote a query in the search input and when I pressed the enter key, I was redirected to "/products?q=query"

**Review by e-azocar — APPROVED** [review]

**Review by heliomar-pena — CHANGES_REQUESTED** [review]
Just fix the case when I do a search and I think that the pull request can be merged, thanks!

imagen

Search input:
imagen

**Comment by ygamboalh** [comment]
Now when you do a search it redirects to the path /artworks. Please let me know if there´s any other problem.

**Review by heliomar-pena — APPROVED** [review]
Very thanks for the changes. Good work!

**Pull request merged**
