### PR TITLE
Added new colors to register page

### LINKED ISSUE #47: Registration Page Styles
### Explanation:
Make style changes to this page, such as text fields, rounded corners, change button style, text styles, and color. Attached figma link to verify design and styles.
### Screenshots
image

image

### Checklist 
 - [ ] Change the background color of the ´#F8F1F1´ text fields.
 - [ ] Set text field border 1px color ´#11698E´.
 - [ ] Text color used in the fields and font color: ´#414141´ and regular Roboto font.
 - [ ] Change the font of the title of the text styles Roboto color in bold.
 - [ ] ´#11698E´ computer text in regular style.
 - [ ] Change the color of the button styles ´#19456B´.
 
### References
https://www.figma.com/file/zzEwuPfGTiZh4EA11MyZ5c/Sencico?node-id=126%3A897

### PR DESCRIPTION
**Pull request by Allislove**
### Description

Please include a summary of the change.
Added new specific colors to register page!
fixes # (#47 ) 

#### Screenshots

If applicable, add screenshots about your changes

#### Type of change
Just added a litte of css
Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

### How to test it

If applicable, describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

1. Log-In how admin.
2. Go to settings.
3. Change admin name.

### Checklist:

- [ ] Doesn't break the current code.
- [ ] Passes linters and test, also is building.
- [DONE ] Doesn't have spelling or grammatical problems.
- [DONE ] Doesn't have unnecessary comments or debugging code.
- [ DONE] The branch is updated with the last dev branch changes.

### CODE REVIEW

**Review by heliomar-pena — COMMENTED** [review]
Styles in the register button are missed. Good work with all the other things! 

imagen

**Comment by angelik0828** [comment]
I am pending change of color in text for the rest I see it very well, great job !!
image

**Comment by Allislove** [comment]
Done!

**Review by heliomar-pena — APPROVED** [review]
Good work!

**Pull request merged**
