### PR TITLE
Added linter configuration

### PR DESCRIPTION
**Pull request by e-azocar**
### Description

I added eslint as Javascript code linter. It's my configuration, but, the idea is build a good configuration that everyone can use.

Please add your comments and your suggestion changes

### CODE REVIEW

**Review by heliomar-pena — APPROVED** [review]
Looks good!

**Comment by e-azocar** [comment]
### Eslint Rules documentation:
https://eslint.org/docs/rules/

We are using currently this configuration
```javascript
{
    indent: ['error', 2],
    quotes: ['error', 'single'],
    semi: ['error', 'always'],
    'comma-dangle': ['error', {
      arrays: 'only-multiline',
      objects: 'only-multiline',
      imports: 'never',
      exports: 'never',
      functions: 'never',
    }],
    'space-before-function-paren': ['error', {
      anonymous: 'always',
      named: 'never',
      asyncArrow: 'always',
    }],
    'multiline-ternary': ['error', 'always'],
    'react/prop-types': 0,
    'node/no-callback-literal': 'off'
}
```

**Review by Israel-Laguan — APPROVED** [review]

**Comment by Israel-Laguan** [comment]
image

Seems like is not building properly, please run 'npm run build' locally and debug

**Comment by Israel-Laguan** [comment]
@e-azocar @Katsu08 please check if this PR can be merged

**Comment by heliomar-pena** [comment]
Now is building correctly
image

**Pull request merged**
