### PR TITLE
Feat/#10

### LINKED ISSUE #10: Update and Check The Breadcrump
### Explanation
The breadcrumbs are used so that the user can locate the content that they want to visit on the web page. In this case home, catalog, minimalist and Adrian Olichon. so the user can quickly go to the content they want to see in a quick and concise way.

### Screenshots
image

### Checklist

- [ ] The words home, catalog, minimalist and Adrián Olichon work in the form of buttons

- [ ] Each word frames a specific content

- [ ] breadcrumbs are at the top of page 4

### References
https://www.figma.com/file/zzEwuPfGTiZh4EA11MyZ5c/Sencico?node-id=65%3A51

### PR DESCRIPTION
**Pull request by Allislove**
Added links to sections a elements!

fixes #10

### CODE REVIEW

**Review by Israel-Laguan — APPROVED** [review]
Maybe check linter, but looks good

@e-azocar @angelik0828 @Katsu08 please check visually

**Comment by e-azocar** [comment]
@Allislove can you add a "/" between the category and the product name?

For example "Categoría / Nombre del Producto"

image

**Comment by Allislove** [comment]
Can you review pls!

**Review by heliomar-pena — CHANGES_REQUESTED** [review]
Good job with the functionality! Can you now add the styles how is in Figma?

I think the text just need to have the gray color that is in the design

imagen

**Comment by Allislove** [comment]
Done

**Review by Israel-Laguan — APPROVED** [review]

**Review by e-azocar — APPROVED** [review]

**Review by heliomar-pena — APPROVED** [review]
Good job! @angelik0828 please check and this can be merged

**Comment by angelik0828** [comment]
I checked but the bold is still missing in the text. @Allislove
image
image

**Pull request merged**
