### PR TITLE
Update Products feat/#33

### LINKED ISSUE #33: Fix Selected Category Title  Styles In Product View.
## Explanation:

When the resolution changes to 1024x717, the width of the title does not get 100% of the container div.
The selected category title should have rounded edges to resemble the [figma design](https://www.figma.com/file/zzEwuPfGTiZh4EA11MyZ5c/Sencico?node-id=65%3A51)

## Screenshots

imagen

## How to reproduce:

1. Enter in this link https://art-marketplace.pages.dev/products?category=26
2. Change the screen size to 1024px width.

## Checklist

- [x] The title of the selected category occupies 100% of the container.
- [x] The border of the title of the selected category is rounded as the design of the figure.

### PR DESCRIPTION
**Pull request by carlosluis911207**
### Explanation

I have added rounded border to the title of selected filter in Products view.

fixes #33 

#### Screenshot

screm#33

#### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)

### How to test it
1.  Enter in this link https://art-marketplace.pages.dev/products?category=26
2.  Change the screen size to 1024px width.

### CODE REVIEW

**Comment by heliomar-pena** [comment]
Please add a description and better title to improve the reviewers experience

**Review by heliomar-pena — APPROVED** [review]
Good job! Please improve description and title to have a good history of changes

**Comment by heliomar-pena** [comment]
You can use how guide this file to do the Pull Request description:

https://raw.githubusercontent.com/Azordev/art-marketplace/dev/.github/pull_request_template.md

**Comment by carlosluis911207** [comment]
screm#33

#### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)

### How to test it
1.  Enter in this link https://art-marketplace.pages.dev/products?category=26
2.  Change the screen size to 1024px width.

**Review by e-azocar — APPROVED** [review]

**Pull request merged**
