### PR TITLE
Remoev unused files

### LINKED ISSUE #54: Remove HomeSlider.jsx From The Project.
### Explanation:

This component is no longer used because we now use a library to handle the sliders. So that it can be removed from the project, keep it clean.

### Checklist
 This issue can be closed when the following tasks are completed:
 
 - [ ] Delete the HomeSlider.jsx file.
 - [ ] Remove HomeSlider.jsx from index.js file.
 - [ ] Delete HomerSlider.test.js

#### Related issues:
 - #55

### PR DESCRIPTION
**Pull request by Allislove**
### Description

Removed unused files

fixes #54 #55 #58

### Checklist:

- [ ] Doesn't break the current code.
- [ ] Passes linters and test, also is building.
- [ ] Doesn't have spelling or grammatical problems.
- [ ] Doesn't have unnecessary comments or debugging code.
- [ X] The branch is updated with the last dev branch changes.

### CODE REVIEW

**Comment by Allislove** [comment]
@e-azocar @Katsu08  Can you review this please!

**Comment by heliomar-pena** [comment]
I'm getting error @Allislove 

imagen

**Comment by Katsu08** [comment]
It's working fine in cloudflare deploy

imagen

**Comment by Allislove** [comment]
I think this can be a API problem! The code is good.

**Comment by Israel-Laguan** [comment]
@Katsu08 its working again on my side, maybe was a temporal issue on API side

**Review by Israel-Laguan — APPROVED** [review]

**Review by e-azocar — APPROVED** [review]
Everything works correctly, @Allislove good job😎

**Pull request merged**
