### PR TITLE
feat: footer buttons look poorly positioned

### LINKED ISSUE #66: Footer Buttons Look Poorly Positioned.
**Describe The Bug**
When I scrolled down to the art market footer, I noticed that the buttons look weird, "Login" is right-aligned and "Sign Up" is left-aligned. I feel this is not friendly to the user.

**To Reproduce**
1. Go to art-marketplace.pages.dev/.
2. Scroll down to footer.

**Expected Behavior**
The behavior is expected to be as shown in [figma].
(https://www.figma.com/file/zzEwuPfGTiZh4EA11MyZ5c/Sencico?node-id=65%3A2), por favor revise en el apartado de imágenes

**Screenshots**
imagen

### PR DESCRIPTION
**Pull request by arodriguezl9302**
### Description

Fixed footer buttons issue

fixes #66 

#### Screenshots

after adjusting the alignment of the buttons, it looks like this
image

I had to add an h-14 to make it take the ideal shape
image

#### Type of change

Please delete options that are not relevant.

Bug fix (non-breaking change which fixes an issue)

### How to test it

If applicable, describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

1. Go to art-marketplace.pages.dev/.

### Checklist:

- [x] Adjust button alignment

### CODE REVIEW

**Comment by Israel-Laguan** [comment]
Looks fine on mobile too 
image

**Comment by Israel-Laguan** [comment]
Why is `yarn.lock` modified? Please check, maybe was not intended

**Comment by arodriguezl9302** [comment]
@Israel-Laguan I haven't touched that file, I don't even work with yarn

**Review by heliomar-pena — APPROVED** [review]
Please remove yarn lock changes from pr

**Pull request merged**
